### ISSUE TITLE
Will HPyD be updated later?

### ISSUE THREAD

**Issue by zzwei1** [CAM-Gerlach/HPyD#1]
Hi, I'm a freshman in radar meteorology, and now I'm studying hydrometeor classification algorithms, and I found your HPyD a useful tool to learn from its introduction, so will you update HPyD  before long?Thank you in advance.

**Comment by CAM-Gerlach** [comment]
@zzwei1 Hey, I actually had an initial implementation done over a year ago as a class project, but I realized I never pushed it to the repo, likely because I did the initial work in a week of consecutive all-nighters and it ended up being a horrific, hacked together out of desperation mess of procedural, non-modular, non-functional, and unstructured code, to the point where it was essentially useless to anyone else given it was not only not terrible resuable, but a horrible example to replicate.

As such I haven't really touched it since like I originally planned to (and the performance wasn't great either), but since you asked I actually pushed it to the repo. Please, don't emulate anything like this, unless you want everyone to groan and cringe. If you want to see an example of some properly done code, check out what I've done under the [HAMMA Dev Org](https://github.com/hamma-dev). Best of luck in your work!

**Comment by CAM-Gerlach** [comment]
And if you want a vastly better example of HID that's not only useful in research and operations, but also as a reusable library you can use with your own work, check out [CSU_radartools](https://github.com/CSU-Radarmet/CSU_RadarTools); my relatively small contributions there still amount to more than this steaming pile of garbage, heh.

**Comment by zzwei1** [comment]
Thanks a lot! I have noticed the csu_radar_tools used the fuzzy logic algorithm to do hydrometeor classification, and I wonna combine the fuzzy logic algorithm with other popular machine learning classification algorithms(like kNN,SVM), but I don't know how to combine now.And I will study your HAMMA Dev Org!😁Thank you again!
